jobs:
  build:
    docker:
      - image: circleci/<python>:<3.8.5>
    steps:
      - checkout
      - run: my-command
  test:
    docker:
      - image: circleci/<python>:<3.8.5>
    steps:
      - checkout
      - run: my-command
        command:
          pip install pipenv
          pipenv install --system
          pipenv run pytest


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
