version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pipenv
            pipenv install --system
      - run:
          name: "Run tests"
          command: |
            . venv/bin/activate
            python -m unittest