version: 2.1
jobs:
  runtests:
  docker:
    -image: circleci/python:3.8.5
  steps:
    -checkout
    - run:
      name: Install python dependencies
      command:
            pip install pipenv
            pipenv install --system
            pipenv run pytest
    - run:
      command: |
            pipenv run pytest


