version: 2.1
jobs:
  runtests:
  docker:
    -image: circleci/python:3.8.5
  steps:
    -checkout
    - run:
      name: Install python dependencies
      command:
            pip install pipenv
            pipenv install --system
            pipenv run pytest
    - run:
        name: Run Unit Tests
        command:
          pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_reporter.html --self-contained-html
    store_test_reults:
      path: test-reports
    store-artifacts:
      path: test-reports
